name: Tests for registration

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - first_test
          - second_test
          - all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests/test_button.py::test_join_us --alluredir=allure-results
      - name: Run tests
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_button.py::test_join_us_9 --alluredir=allure-results